global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sentinel-services"
    static_configs:
      - targets:
          - "api-gateway:8000"
          - "user-service:8000"
          - "order-service:8000"
          - "payment-service:8000"
          - "notification-service:8000"
